# Generated by Django 2.1.5 on 2019-02-10 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴 카테고리')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴 이름')),
                ('is_event', models.BooleanField(verbose_name='행사 중인가?')),
                ('price', models.CharField(max_length=50, verbose_name='가격')),
                ('event_price', models.CharField(max_length=50, verbose_name='행사 가격')),
                ('image', models.CharField(max_length=100, verbose_name='상품 이미지')),
                ('is_selling', models.BooleanField(verbose_name='아직 파는 중인가?')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Category', verbose_name='카테고리 id')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='가게 이름')),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='가게 타입')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='storetype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.StoreType', verbose_name='가게 종류'),
        ),
        migrations.AddField(
            model_name='menu',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Store', verbose_name='가게 id'),
        ),
        migrations.AddField(
            model_name='category',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Store', verbose_name='가게 id'),
        ),
    ]
