# Generated by Django 2.1.5 on 2019-02-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='storetype_id',
            new_name='storetype',
        ),
    ]
