# Generated by Django 2.1.5 on 2019-02-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20190211_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='event_price',
            field=models.CharField(default='', max_length=50, verbose_name='행사 가격'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='행사 중인가?'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_selling',
            field=models.BooleanField(default=True, verbose_name='아직 파는 중인가?'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(default='', max_length=50, verbose_name='가격'),
        ),
    ]
