# Generated by Django 2.1.7 on 2019-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_auto_20190211_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지'),
        ),
    ]
